[supabase]
url = "https://ohjgnbfodylmfismcwde.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oamduYmZvZHlsbWZpc21jd2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MTk2NDQsImV4cCI6MjA3NzM5NTY0NH0.hyvTH5v7wlbkH9ixarjCjKyTiDfiTRyux4rUEsNqm5A"
